# data = ["Id  ", "HoleNum  ", "NozzleType  ", "x  ", "y  ", "ATPGroup  ", "InsertionDT  "]
# data.extend(["InsertionForce  ", "InsertionForcePass  ", "P1SResult  ", "P2SResult  ", "P2Pass  "])
# data.extend(["P2TestDT  ", "P4Result  ", "P4SResult  ", "P4Pass ", "P4TestDT  ", "Faulted  ", "ErrorReason  "])
# data.extend(["IsLong  ", "actualX  ", "actualY  ", "TraySN  ", "TrayPosition  ", "forceFailsQty  "])
# data.extend(["batchNum  ", "trayRerunNum  ", "M1P1Result  ", "M1P2Result  ", "M1NozzleAddressInTray  "])
# data.extend(["insertionTemperature  ", "P3Result  ", "P3SResult  ", "P3Pass  ", "P3TestDT  "])
# data.extend(["pressureFailsQty  ", "pressureFailsQty4  ", "pressureFailsQty3  ", "PlatesId  "])

data=["OK = 0"]
data.append("NozzleWasDetectedInPlateHole = 1")
data.append("NoHoleWasDetectedInPlate = 2")
data.append("PlateHoleIsTooBigForShortNozzle = 3")
data.append("PlateHoleIsTooSmallForLongNozzle = 4")
data.append("XPlateHolePositionDeviationIsTooBig = 5")
data.append("YPlateHolePositionDeviationIsTooBig = 6")
data.append("XandYPlateHolePositionDeviationIsTooBig = 7")
data.append("TBD8 = 8")
data.append("TBD9 = 9")
data.append("NozzlePlacingInPlateWasInterrupted = 10")
data.append("InsertionForceIsTooHigh = 11")
data.append("InsertionForceIsTooLow = 12")
data.append("InsertionDepthIsTooDeep = 13")
data.append("InsertionDepthIsTooShallow = 14")
data.append("NozzleWasStickingOutOfThePlate = 15")
data.append("ToolAlarmOrBushingHeightLowWhilePlenting = 16")
data.append("IncorrectForceData = 17")
data.append("BushingHeadAasBlockedByNozzle = 18")
data.append("ContinueWithUnfinishedProcess = 19")
data.append("IncorrectPressureData = 20")
data.append("P1StoP2SLowRatioResult = 21")
data.append("P1StoP2SHighRatioResult = 22")
data.append("ATPIndividualP3P3STLowRatioResult = 23")
data.append("ATPIndividualP3P3STHiRatioResult = 24")
data.append("TBD25 = 25")
data.append("TBD26 = 26")
data.append("TBD27 = 27")
data.append("TBD28 = 28")
data.append("TBD29 = 29")
data.append("TBD30 = 30")
data.append("P4toP4STLowRatioResult = 31")
data.append("P4toP4STHighRatioResult = 32")
data.append("TBD33 = 33")
data.append("UnknownFailureReason = 34")
data.append("NoHoleWasDetectedInPlate_ProductManagerApproval = 102")
data.append("PlateHoleIsTooBigForShortNozzle_ProductManagerApproval = 103")
data.append("PlateHoleIsTooSmallForLongNozzle_ProductManagerApproval = 104")
data.append("NotYetSet = 1000")
data.append("PlasticSkip = 100")

for str in data:
    parts = [x for x in str.split(' =') if x]
    print ('{{ {1},"{0}" }},'.format(parts[0], parts[1]))